### ISSUE TITLE
Can't set strategy options at runtime

### ISSUE THREAD

**Issue by mustela** [jjcarstens/ueberauth_okta#16] opened 2022-11-30 09:26 UTC
Hello there!  After upgrading to 1.0 I can no longer set the settings at runtime. Before the latest release I had: 

`config.exs`

```
config :ueberauth, Ueberauth,
  base_path: "/oauth",
  providers: [
    okta: {
      Ueberauth.Strategy.Okta,
      [
        oauth2_params: [scope: "openid email"]
      ]
    }
  ]
```

`runtime.exs`
```

config :ueberauth, Ueberauth.Strategy.Okta.OAuth,
  site: System.get_env("OKTA_CLIENT_SITE"),
  client_id: System.get_env("OKTA_CLIENT_ID"),
  client_secret: System.get_env("OKTA_CLIENT_SECRET")  

```

Using 1.0 Im doing: 

`config.exs`

```
config :ueberauth, Ueberauth,
  base_path: "/oauth",
  providers: [ # it fails if I don't set the providers key
    okta: {
      Ueberauth.Strategy.Okta,
      []
    }
  ]
```

`runtime.exs`

```
config :ueberauth, Ueberauth,
        base_path: "/oauth",
        providers: [
          okta:
            {Ueberauth.Strategy.Okta,
             [
               site: System.get_env("OKTA_CLIENT_SITE"),
               client_id: System.get_env("OKTA_CLIENT_ID"),
               client_secret: System.get_env("OKTA_CLIENT_SECRET")
             ]}
        ]
```

But I keep getting 
```
Request: GET /oauth/okta
12 ** (exit) an exception was raised:
11** (RuntimeError) [Ueberauth.Strategy.Okta.OAuth] missing required key: :client_id
10    (ueberauth_okta 1.0.0) lib/ueberauth/strategy/okta/oauth.ex:124: Ueberauth.Strategy.Okta.OAuth.validate_config_option!/2
9    (ueberauth_okta 1.0.0) lib/ueberauth/strategy/okta/oauth.ex:57: Ueberauth.Strategy.Okta.OAuth.client/1
8    (ueberauth_okta 1.0.0) lib/ueberauth/strategy/okta/oauth.ex:70: Ueberauth.Strategy.Okta.OAuth.authorize_url!/2
7    (ueberauth_okta 1.0.0) lib/ueberauth/strategy/okta.ex:152: Ueberauth.Strategy.Okta.handle_request!/1
6    (identity_gate 0.1.2) MyAppWeb.Router.auth/2
5    (identity_gate 0.1.2) lib/my_app_web/router.ex:1: MyAppWeb.Router.__pipe_through0__/1
4    (phoenix 1.6.15) lib/phoenix/router.ex:346: Phoenix.Router.__call__/2
3    (identity_gate 0.1.2) lib/my_app_web/endpoint.ex:1: MyAppWeb.Endpoint.plug_builder_call/2
2 09:15:50.751 request_id=20f9af1083ccbdf6a55d92a4ea04a5e2 [info] GET /css/app.css
1 09:15:50.751 request_id=20f9af1083ccbdf6a55d92a4ea04a5e2 [info] Sent 404 in 99µs
```

Any idea how can keep having the configuration in the runtime file? 

Thanks!

**Comment by jjcarstens** [comment] 2022-11-30 13:04
👋🏼 hey @mustela! I think I would need an example project that reproduces this to better help. When I use you're configuration above, then it works for me. Maybe there is configuration getting applied later on that is wiping out what you have above?

**Comment by mustela** [comment] 2022-11-30 23:07
@jjcarstens here you have the [example project](https://github.com/mustela/okta-test#build-the-image). 

The configuration is working when using dev, but not when building it and using prod. If you build the image and run the container you will be able to replicate the error. Hit the sign in button. 

![Screenshot 2022-12-01 at 00 06 00](https://user-images.githubusercontent.com/325222/204927197-bbee7855-1389-4d31-ab94-5c293b2cd8c5.png)


Thanks a lot!

**Comment by jjcarstens** [comment] 2022-12-01 13:39
Ah, so it looks like the culprit is because the `c:Plug.init/1` can be called during compile time (see [Plug docs](https://hexdocs.pm/plug/1.14.0/Plug.html#module-plugs))

> _The result returned by [init/1](https://hexdocs.pm/plug/1.14.0/Plug.html#c:init/1) is passed as second argument to [call/2](https://hexdocs.pm/plug/1.14.0/Plug.html#c:call/2). Note that [init/1](https://hexdocs.pm/plug/1.14.0/Plug.html#c:init/1) may be called during compilation and as such it must not return pids, ports or values that are specific to the runtime._

It seems behavior is different when `MIX_ENV=prod` and those values are indeed missing from the ueberauth options in the plug. I'm not sure how to solve quite yet and need to think on this a bit. Maybe compare what others are doing

**Comment by mustela** [comment] 2022-12-01 15:08
Thanks Jon, Im not too familiar with how ueberauth strategies works, but Ill explore others and see if I can understand the difference with yours.

**Comment by jjcarstens** [comment] 2022-12-29 15:28
Resolved with #17

**Closed by jjcarstens** 2022-12-29 15:28 UTC

**Comment by paulkapustin** [comment] 2023-06-29 20:37
@jjcarstens Unfortunately, the fix doesn't seem to work for me.

When I try these snippets:

```
config :ueberauth, Ueberauth,
  providers: [
    okta: {Ueberauth.Strategy.Okta, []}
  ]

config :ueberauth, Ueberauth.Strategy.Okta.OAuth,
  site: System.get_env("OKTA_SITE"),
  client_id: System.get_env("OKTA_CLIENT_ID"),
  client_secret: System.get_env("OKTA_CLIENT_SECRET")
```

Or:

```
config :ueberauth, Ueberauth,
  providers: [
    okta: {Ueberauth.Strategy.Okta, []}
  ]

config :ueberauth, Ueberauth.Strategy.Okta.OAuth,
  okta: [
    site: System.get_env("OKTA_SITE"),
    client_id: System.get_env("OKTA_CLIENT_ID"),
    client_secret: System.get_env("OKTA_CLIENT_SECRET")
  ]

```

I get:

```
Request: GET /auth/okta/callback?code=EvtJr4Fk4seZoCwCpsccAaGLqfFYpybLGWrdZQk1rkE&state=vvVw2QzXkzEN8lIQOA0MI6wf
** (exit) an exception was raised:
    ** (RuntimeError) [Ueberauth.Strategy.Okta.OAuth] missing required key: :client_id 
        (ueberauth_okta 1.1.1) lib/ueberauth/strategy/okta/oauth.ex:128: Ueberauth.Strategy.Okta.OAuth.validate_config_option!/2
        (ueberauth_okta 1.1.1) lib/ueberauth/strategy/okta/oauth.ex:61: Ueberauth.Strategy.Okta.OAuth.client/1
        (ueberauth_okta 1.1.1) lib/ueberauth/strategy/okta/oauth.ex:84: Ueberauth.Strategy.Okta.OAuth.get_user_info/2
        (ueberauth_okta 1.1.1) lib/ueberauth/strategy/okta.ex:184: Ueberauth.Strategy.Okta.fetch_user/2
        (ueberauth 0.10.5) lib/ueberauth/strategy.ex:376: Ueberauth.Strategy.run_handle_callback/2
        (campaign_service 0.1.0) CampaignServiceWeb.Router.browser/2
        (campaign_service 0.1.0) lib/campaign_service_web/router.ex:1: CampaignServiceWeb.Router.__pipe_through2__/1
        (phoenix 1.7.2) lib/phoenix/router.ex:421: Phoenix.Router.__call__/5
        (campaign_service 0.1.0) lib/campaign_service_web/endpoint.ex:1: CampaignServiceWeb.Endpoint.plug_builder_call/2
        (campaign_service 0.1.0) lib/campaign_service_web/endpoint.ex:1: CampaignServiceWeb.Endpoint."call (overridable 3)"/2
        (campaign_service 0.1.0) deps/plug/lib/plug/debugger.ex:136: CampaignServiceWeb.Endpoint."call (overridable 4)"/2
        (campaign_service 0.1.0) lib/campaign_service_web/endpoint.ex:1: CampaignServiceWeb.Endpoint.call/2
        (phoenix 1.7.2) lib/phoenix/endpoint/sync_code_reload_plug.ex:22: Phoenix.Endpoint.SyncCodeReloadPlug.do_call/4
        (plug_cowboy 2.6.1) lib/plug/cowboy/handler.ex:11: Plug.Cowboy.Handler.init/2
        (cowboy 2.9.0) /Users/paulkapustin/src/campaign-service/deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2
        (cowboy 2.9.0) /Users/paulkapustin/src/campaign-service/deps/cowboy/src/cowboy_stream_h.erl:306: :cowboy_stream_h.execute/3
        (cowboy 2.9.0) /Users/paulkapustin/src/campaign-service/deps/cowboy/src/cowboy_stream_h.erl:295: :cowboy_stream_h.request_process/3
        (stdlib 4.3.1.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
```

If I don't use `Ueberauth.Strategy.Okta.OAuth`, the configuration is not correctly read at runtime (leading to `missing required key: :client_id` error either before authenticating with Okta or during the callback from Okta.

Any help is highly appreciated. 
Thanks!

**Comment by pkapustin** [comment] 2023-06-29 20:39
@jjcarstens Unfortunately, the fix doesn't seem to work for me.

When I try these snippets:

```
config :ueberauth, Ueberauth,
  providers: [
    okta: {Ueberauth.Strategy.Okta, []}
  ]

config :ueberauth, Ueberauth.Strategy.Okta.OAuth,
  site: System.get_env("OKTA_SITE"),
  client_id: System.get_env("OKTA_CLIENT_ID"),
  client_secret: System.get_env("OKTA_CLIENT_SECRET")
```

Or:

```
config :ueberauth, Ueberauth,
  providers: [
    okta: {Ueberauth.Strategy.Okta, []}
  ]

config :ueberauth, Ueberauth.Strategy.Okta.OAuth,
  okta: [
    site: System.get_env("OKTA_SITE"),
    client_id: System.get_env("OKTA_CLIENT_ID"),
    client_secret: System.get_env("OKTA_CLIENT_SECRET")
  ]

```

I get:

```
Request: GET /auth/okta/callback?code=EvtJr4Fk4seZoCwCpsccAaGLqfFYpybLGWrdZQk1rkE&state=vvVw2QzXkzEN8lIQOA0MI6wf
** (exit) an exception was raised:
    ** (RuntimeError) [Ueberauth.Strategy.Okta.OAuth] missing required key: :client_id 
        (ueberauth_okta 1.1.1) lib/ueberauth/strategy/okta/oauth.ex:128: Ueberauth.Strategy.Okta.OAuth.validate_config_option!/2
        (ueberauth_okta 1.1.1) lib/ueberauth/strategy/okta/oauth.ex:61: Ueberauth.Strategy.Okta.OAuth.client/1
        (ueberauth_okta 1.1.1) lib/ueberauth/strategy/okta/oauth.ex:84: Ueberauth.Strategy.Okta.OAuth.get_user_info/2
        (ueberauth_okta 1.1.1) lib/ueberauth/strategy/okta.ex:184: Ueberauth.Strategy.Okta.fetch_user/2
        (ueberauth 0.10.5) lib/ueberauth/strategy.ex:376: Ueberauth.Strategy.run_handle_callback/2
        (campaign_service 0.1.0) CampaignServiceWeb.Router.browser/2
        (campaign_service 0.1.0) lib/campaign_service_web/router.ex:1: CampaignServiceWeb.Router.__pipe_through2__/1
        (phoenix 1.7.2) lib/phoenix/router.ex:421: Phoenix.Router.__call__/5
        (campaign_service 0.1.0) lib/campaign_service_web/endpoint.ex:1: CampaignServiceWeb.Endpoint.plug_builder_call/2
        (campaign_service 0.1.0) lib/campaign_service_web/endpoint.ex:1: CampaignServiceWeb.Endpoint."call (overridable 3)"/2
        (campaign_service 0.1.0) deps/plug/lib/plug/debugger.ex:136: CampaignServiceWeb.Endpoint."call (overridable 4)"/2
        (campaign_service 0.1.0) lib/campaign_service_web/endpoint.ex:1: CampaignServiceWeb.Endpoint.call/2
        (phoenix 1.7.2) lib/phoenix/endpoint/sync_code_reload_plug.ex:22: Phoenix.Endpoint.SyncCodeReloadPlug.do_call/4
        (plug_cowboy 2.6.1) lib/plug/cowboy/handler.ex:11: Plug.Cowboy.Handler.init/2
        (cowboy 2.9.0) /Users/paulkapustin/src/campaign-service/deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2
        (cowboy 2.9.0) /Users/paulkapustin/src/campaign-service/deps/cowboy/src/cowboy_stream_h.erl:306: :cowboy_stream_h.execute/3
        (cowboy 2.9.0) /Users/paulkapustin/src/campaign-service/deps/cowboy/src/cowboy_stream_h.erl:295: :cowboy_stream_h.request_process/3
        (stdlib 4.3.1.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
```

If I don't use `Ueberauth.Strategy.Okta.OAuth`, the configuration is not correctly read at runtime (leading to `missing required key: :client_id` error either before authenticating with Okta or during the callback from Okta.

Any help is highly appreciated. 
Thanks!

**Comment by andyleclair** [comment] 2023-06-30 19:51
@jjcarstens we are also running into the same error. We don't see any issues on `0.3.x` fwiw

**Comment by andyleclair** [comment] 2023-06-30 20:00
@jjcarstens we (Appcues) would also be willing to take ownership of this repo and maintain it if you don't want to. We use Okta and we use this plugin, so it'd be a good fit

**Comment by pkapustin** [comment] 2023-06-30 20:57
@andyleclair Do you mean that it works for you with reading runtime configuration on version 0.3.x of this plugin?

**Comment by andyleclair** [comment] 2023-07-06 13:49
@pkapustin yes using version `0.3.1` works as advertised. We (Appcues) have taken over the maintenance of this plugin (we use it!) so we'll get to the bottom of the issue and release a new version. In the meantime, `0.3.x` works
